<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\Query;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Query
     */
    public function findAllproductsOrderedByNewest()
    {
        return $this->createQueryBuilder('product')
            ->orderBy('product.createdDate', 'DESC')
            ->getQuery();
    }
}
